Add files via upload
All scripts have been updated to 1.1 with minor code improvements, plus the following:
MPVCLIP/MPVLOOP
- fixed -s option not playing files with MPV profiles entered on the command line.
MPVIVAL
- filenames are no longer printed along with clip/loop pattern playlists.

diff --git a/mpvclipf b/mpvclipf
--- a/mpvclipf
+++ b/mpvclipf
@@ -22,12 +22,10 @@ q=1
 # Field delimiter in a playlist
 d=,
 
-scr1pt() {
-	basename "$0"
-}
+scp="$(basename "$0")"
 
 if [ "$#" -eq 0 ] ; then
-	echo "$(scr1pt): Usage: $(scr1pt) {[<mpv profile,...>] <tag> [-p <pattern> | -l] [-s] [path/]filename | --help | --version}"
+	echo "${scp}: Usage: ${scp} {[<mpv profile,...>] <tag> [-p <pattern> | -l] [-s] [path/]filename | --help | --version}"
 	exit
 elif [ '--help' = "$1" ] ; then
 	cat << '_EOF_'
@@ -125,7 +123,7 @@ provided without warranty of any kind.
 _EOF_
 	exit
 elif [ '--version' = "$1" ] ; then
-	echo "mpvclipf 1.0"
+	echo "mpvclipf 1.1"
 	exit
 fi
 
@@ -138,14 +136,14 @@ swreq() {
 }
 
 uquit() {
-	echo "$(scr1pt): INFO: Press any key to exit the script or skip the file."
+	echo "${scp}: INFO: Press any key to exit the script or skip the file."
 	if read -rst "$q" -N 1 ; then
-		echo "$(scr1pt): File: $f1"
-		echo "$(scr1pt): Please confirm:"
+		echo "${scp}: File: $f1"
+		echo "${scp}: Please confirm:"
 		select ans in "EXIT the script" "SKIP file" "Cancel" ; do
 			case "$ans" in
 				'EXIT the script' )
-					echo "$(scr1pt): $((iterout - 1)) iterations completed - exiting..."
+					echo "${scp}: $((iterout - 1)) iterations completed - exiting..."
 					exit;;
 				'SKIP file' )
 					return 1;;
@@ -167,10 +165,10 @@ core_ll() {
 		f1="$(cut -d "$d" -f 1 <<< "$line")"
 		if [ ! -f "$f1" ] || grep -qv "$d" <<< "$line" ; then
 			if [ ${#line} -gt 90 ] ; then
-				echo >&2 "$(scr1pt): WARNING: No field separator or file - skipping: ${line:0:45}...${line: -45}"
+				echo >&2 "${scp}: WARNING: No field separator or file - skipping: ${line:0:45}...${line: -45}"
 				continue
 			else
-				echo >&2 "$(scr1pt): WARNING: No field separator or file - skipping: $line"
+				echo >&2 "${scp}: WARNING: No field separator or file - skipping: $line"
 				continue
 			fi
 		fi
@@ -185,8 +183,8 @@ core_ll() {
 						continue 2
 					fi
 				fi
-				echo "$(scr1pt): Clip tag: $ltag"
-				echo "$(scr1pt): Starting ${_mpvclip}..."
+				echo "${scp}: Clip tag: $ltag"
+				echo "${scp}: Starting ${_mpvclip}..."
 				"$_mpvclip" "$@" "$ab" "$f1"
 			else
 				continue
@@ -208,22 +206,22 @@ if [ ! -e "$1" ] ; then
 					fi
 					core_ll
 				else
-					echo >&2 "$(scr1pt): WARNING: Empty file: $3"
-					echo "$(scr1pt): Help summary: $(scr1pt) --help"
+					echo >&2 "${scp}: WARNING: Empty file: $3"
+					echo "${scp}: Help summary: ${scp} --help"
 				fi
 			else
-				echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist: $3"
-				echo "$(scr1pt): Help summary: $(scr1pt) --help"
+				echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist: $3"
+				echo "${scp}: Help summary: ${scp} --help"
 			fi
 		else
 			shift 2
-			echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist:" "$@"
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist:" "$@"
+			echo "${scp}: Help summary: ${scp} --help"
 		fi
 		if [ -v iterout ] ; then
-			echo "$(scr1pt): $iterout iterations completed - exiting..."
+			echo "${scp}: $iterout iterations completed - exiting..."
 		else
-			echo >&2 "$(scr1pt): WARNING: Tag or pattern not found - exiting..."
+			echo >&2 "${scp}: WARNING: Tag or pattern not found - exiting..."
 		fi
 	elif [ '-p' = "$2" ] && [ -e "$4" ] || [ '-s' = "$4" ] ; then
 		ltag="$1"
@@ -251,7 +249,7 @@ if [ ! -e "$1" ] ; then
 						continue
 					fi
 				else
-					echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+					echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 				fi
 			done
 			if [ -v shuffle ] ; then
@@ -260,8 +258,8 @@ if [ ! -e "$1" ] ; then
 				iall1+=("${iall2[@]}")
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: Invalid options - aborting."
+			echo "${scp}: Help summary: ${scp} --help"
 			exit 1
 		fi
 		for f1 in "${iall1[@]}" ; do
@@ -274,15 +272,15 @@ if [ ! -e "$1" ] ; then
 						continue 2
 					fi
 				fi
-				echo "$(scr1pt): Clip tag: $ltag"
-				echo "$(scr1pt): Starting ${_mpvclip}..."
+				echo "${scp}: Clip tag: $ltag"
+				echo "${scp}: Starting ${_mpvclip}..."
 				"$_mpvclip" "$ab" "$f1"
 			done
 		done
 		if [ -v iterout ] ; then
-			echo "$(scr1pt): $iterout iterations completed - exiting..."
+			echo "${scp}: $iterout iterations completed - exiting..."
 		else
-			echo >&2 "$(scr1pt): WARNING: Tag or pattern not found - exiting..."
+			echo >&2 "${scp}: WARNING: Tag or pattern not found - exiting..."
 		fi
 	elif [ '-l' = "$3" ] || [ '-ls' = "$3" ] || [ '-sl' = "$3" ] ; then
 		if [ "$#" -eq 4 ] && [ -r "$4" ] ; then
@@ -297,8 +295,8 @@ if [ ! -e "$1" ] ; then
 								ltag="$arg"
 							else
 								if [ -n "$ltag" ] ; then
-									echo >&2 "$(scr1pt): WARNING: Cannot define MPV profile - aborting."
-									echo "$(scr1pt): Help summary: $(scr1pt) --help"
+									echo >&2 "${scp}: WARNING: Cannot define MPV profile - aborting."
+									echo "${scp}: Help summary: ${scp} --help"
 									exit 1
 								fi
 							fi
@@ -314,22 +312,22 @@ if [ ! -e "$1" ] ; then
 					fi
 					core_ll "$prf"
 				else
-					echo >&2 "$(scr1pt): WARNING: Empty file: $4"
-					echo "$(scr1pt): Help summary: $(scr1pt) --help"
+					echo >&2 "${scp}: WARNING: Empty file: $4"
+					echo "${scp}: Help summary: ${scp} --help"
 				fi
 			else
-				echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist: $4"
-				echo "$(scr1pt): Help summary: $(scr1pt) --help"
+				echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist: $4"
+				echo "${scp}: Help summary: ${scp} --help"
 			fi
 		else
 			shift 3
-			echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist:" "$@"
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist:" "$@"
+			echo "${scp}: Help summary: ${scp} --help"
 		fi
 		if [ -v iterout ] ; then
-			echo "$(scr1pt): $iterout iterations completed - exiting..."
+			echo "${scp}: $iterout iterations completed - exiting..."
 		else
-			echo >&2 "$(scr1pt): WARNING: Tag or pattern not found - exiting..."
+			echo >&2 "${scp}: WARNING: Tag or pattern not found - exiting..."
 		fi
 	elif [ '-p' = "$3" ] && [ -e "$5" ] || [ '-s' = "$5" ] ; then
 		ppat="$4"
@@ -342,8 +340,8 @@ if [ ! -e "$1" ] ; then
 					ltag="$arg"
 				else
 					if [ -n "$ltag" ] ; then
-						echo >&2 "$(scr1pt): WARNING: Cannot define MPV profile - aborting."
-						echo "$(scr1pt): Help summary: $(scr1pt) --help"
+						echo >&2 "${scp}: WARNING: Cannot define MPV profile - aborting."
+						echo "${scp}: Help summary: ${scp} --help"
 						exit 1
 					fi
 				fi
@@ -376,7 +374,7 @@ if [ ! -e "$1" ] ; then
 						continue
 					fi
 				else
-					echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+					echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 				fi
 			done
 			if [ -v shuffle ] ; then
@@ -385,8 +383,8 @@ if [ ! -e "$1" ] ; then
 				iall1+=("${iall2[@]}")
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: Invalid options - aborting."
+			echo "${scp}: Help summary: ${scp} --help"
 			exit 1
 		fi
 		for f1 in "${iall1[@]}" ; do
@@ -399,15 +397,15 @@ if [ ! -e "$1" ] ; then
 						continue 2
 					fi
 				fi
-				echo "$(scr1pt): Clip tag: $ltag"
-				echo "$(scr1pt): Starting ${_mpvclip}..."
+				echo "${scp}: Clip tag: $ltag"
+				echo "${scp}: Starting ${_mpvclip}..."
 				"$_mpvclip" "$prf" "$ab" "$f1"
 			done
 		done
 		if [ -v iterout ] ; then
-			echo "$(scr1pt): $iterout iterations completed - exiting..."
+			echo "${scp}: $iterout iterations completed - exiting..."
 		else
-			echo >&2 "$(scr1pt): WARNING: Tag or pattern not found - exiting..."
+			echo >&2 "${scp}: WARNING: Tag or pattern not found - exiting..."
 		fi
 	elif [ -e "$2" ] || [ '-s' = "$2" ] ; then
 		ltag="$1"
@@ -434,7 +432,7 @@ if [ ! -e "$1" ] ; then
 						continue
 					fi
 				else
-					echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+					echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 				fi
 			done
 			if [ -v shuffle ] ; then
@@ -443,8 +441,8 @@ if [ ! -e "$1" ] ; then
 				iall1+=("${iall2[@]}")
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: Invalid options - aborting."
+			echo "${scp}: Help summary: ${scp} --help"
 			exit 1
 		fi
 		for f1 in "${iall1[@]}" ; do
@@ -457,15 +455,15 @@ if [ ! -e "$1" ] ; then
 						continue 2
 					fi
 				fi
-				echo "$(scr1pt): Clip tag: $ltag"
-				echo "$(scr1pt): Starting ${_mpvclip}..."
+				echo "${scp}: Clip tag: $ltag"
+				echo "${scp}: Starting ${_mpvclip}..."
 				"$_mpvclip" "$ab" "$f1"
 			done
 		done
 		if [ -v iterout ] ; then
-			echo "$(scr1pt): $iterout iterations completed - exiting..."
+			echo "${scp}: $iterout iterations completed - exiting..."
 		else
-			echo >&2 "$(scr1pt): WARNING: Tag or pattern not found - exiting..."
+			echo >&2 "${scp}: WARNING: Tag or pattern not found - exiting..."
 		fi
 	elif [ ! -e "$2" ] && [ -e "$3" ] || [ '-s' = "$3" ] ; then
 		for arg in "$1" "$2" ; do
@@ -477,8 +475,8 @@ if [ ! -e "$1" ] ; then
 					ltag="$arg"
 				else
 					if [ -n "$ltag" ] ; then
-						echo >&2 "$(scr1pt): WARNING: Cannot define MPV profile - aborting."
-						echo "$(scr1pt): Help summary: $(scr1pt) --help"
+						echo >&2 "${scp}: WARNING: Cannot define MPV profile - aborting."
+						echo "${scp}: Help summary: ${scp} --help"
 						exit 1
 					fi
 				fi
@@ -511,7 +509,7 @@ if [ ! -e "$1" ] ; then
 						continue
 					fi
 				else
-					echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+					echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 				fi
 			done
 			if [ -v shuffle ] ; then
@@ -520,8 +518,8 @@ if [ ! -e "$1" ] ; then
 				iall1+=("${iall2[@]}")
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: Invalid options - aborting."
+			echo "${scp}: Help summary: ${scp} --help"
 			exit 1
 		fi
 		for f1 in "${iall1[@]}" ; do
@@ -534,21 +532,21 @@ if [ ! -e "$1" ] ; then
 						continue 2
 					fi
 				fi
-				echo "$(scr1pt): Clip tag: $ltag"
-				echo "$(scr1pt): Starting ${_mpvclip}..."
+				echo "${scp}: Clip tag: $ltag"
+				echo "${scp}: Starting ${_mpvclip}..."
 				"$_mpvclip" "$prf" "$ab" "$f1"
 			done
 		done
 		if [ -v iterout ] ; then
-			echo "$(scr1pt): $iterout iterations completed - exiting..."
+			echo "${scp}: $iterout iterations completed - exiting..."
 		else
-			echo >&2 "$(scr1pt): WARNING: Tag or pattern not found - exiting..."
+			echo >&2 "${scp}: WARNING: Tag or pattern not found - exiting..."
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 	fi
 else
-	echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-	echo "$(scr1pt): Help summary: $(scr1pt) --help"
+	echo >&2 "${scp}: WARNING: Invalid options - aborting."
+	echo "${scp}: Help summary: ${scp} --help"
 fi
diff --git a/mpvival b/mpvival
--- a/mpvival
+++ b/mpvival
@@ -10,15 +10,13 @@
 # half a second: 0.5
 q=1
 
-scr1pt() {
-	basename "$0"
-}
+scp="$(basename "$0")"
 
 swreq() {
-	type ffprobe >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: FFPROBE not found - aborting."; exit 1; }
-	type grep >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: GREP not found - aborting."; exit 1; }
-	type mpv >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: MPV not found - aborting."; exit 1; }
-	type file >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: FILE (command) not found - aborting."; exit 1; }
+	type ffprobe >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: FFPROBE not found - aborting."; exit 1; }
+	type grep >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: GREP not found - aborting."; exit 1; }
+	type mpv >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: MPV not found - aborting."; exit 1; }
+	type file >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: FILE (command) not found - aborting."; exit 1; }
 }
 
 getdur() {
@@ -85,24 +83,24 @@ getiparam() {
 
 	if ((_length > idur)) ; then
 		_length="$idur"
-		echo "$(scr1pt): INFO: Clip duration reset: ${idur}s"
+		echo "${scp}: INFO: Clip duration reset: ${idur}s"
 	fi
 }
 
 uquit() {
-	echo "$(scr1pt): INFO: Press any key to exit the script or skip the file."
+	echo "${scp}: INFO: Press any key to exit the script or skip the file."
 	if read -rst "$q" -N 1 ; then
-		echo "$(scr1pt): File: $f1"
-		echo "$(scr1pt): Interval: $ival / $ivals ($(((iterin - 1) * idur))-$((idur * iterin))s)"
-		echo "$(scr1pt): Please confirm:"
+		echo "${scp}: File: $f1"
+		echo "${scp}: Interval: $ival / $ivals ($(((iterin - 1) * idur))-$((idur * iterin))s)"
+		echo "${scp}: Please confirm:"
 		select ans in "EXIT the script" "SKIP file" "Cancel" ; do
 			case "$ans" in
 				'EXIT the script' )
-					echo "$(scr1pt): Loop Pattern playlist: ${ff1},$(tr '[:blank:]' ',' <<< "${lpatpl[*]}")"
-					echo "$(scr1pt): $((iterout - 1)) iterations completed - exiting..."
+					echo "${scp}: Clip Pattern playlist: ${lpatpl[*]}"
+					echo "${scp}: $((iterout - 1)) iterations completed - exiting..."
 					exit;;
 				'SKIP file' )
-					echo "$(scr1pt): Loop Pattern playlist: ${ff1},$(tr '[:blank:]' ',' <<< "${lpatpl[*]}")"
+					echo "${scp}: Clip Pattern playlist: ${lpatpl[*]}"
 					return 1;;
 				'Cancel' )
 					break;;
@@ -114,12 +112,12 @@ uquit() {
 
 core() {
 	if [ -z "$dur" ] ; then
-		echo "$(scr1pt): INFO: Total duration unknown - playing video from beginning."
+		echo "${scp}: INFO: Total duration unknown - playing video from beginning."
 	fi
-	echo "$(scr1pt): Interval: $ival / $ivals ($(((iterin - 1) * idur))-$((idur * iterin))s)"
-	echo "$(scr1pt): Options:" "${@:-None}"
-	echo "$(scr1pt): Loop Pattern: $lpat"
-	echo "$(scr1pt): Starting mpv..."
+	echo "${scp}: Interval: $ival / $ivals ($(((iterin - 1) * idur))-$((idur * iterin))s)"
+	echo "${scp}: Options:" "${@:-None}"
+	echo "${scp}: Loop Pattern: $lpat"
+	echo "${scp}: Starting mpv..."
 	mpv "$@" "$f1"
 }
 
@@ -133,12 +131,11 @@ core_llt() {
 		for line in "${iall[@]}" ; do
 			if [ -f "$line" ] ; then
 				f1="$line"
-				ff1="$(realpath -q "$f1")"
 				_length="$_lengtho"
 				dur="$(getdur)"
 				if ((_length > dur)) ; then
 					_length="$dur"
-					echo "$(scr1pt): INFO: Clip duration reset: ${dur}s"
+					echo "${scp}: INFO: Clip duration reset: ${dur}s"
 				fi
 				idur="$dur"
 				ivals="$scal"
@@ -159,9 +156,9 @@ core_llt() {
 			else
 				if grep -q '[^[:space:]]' <<< "$line" ; then
 					if [ ${#line} -gt 90 ] ; then
-						echo >&2 "$(scr1pt): WARNING: Not a regular file - skipping: ${line:0:45}...${line: -45}"
+						echo >&2 "${scp}: WARNING: Not a regular file - skipping: ${line:0:45}...${line: -45}"
 					else
-						echo >&2 "$(scr1pt): WARNING: Not a regular file - skipping: $line"
+						echo >&2 "${scp}: WARNING: Not a regular file - skipping: $line"
 					fi
 				fi
 			fi
@@ -180,7 +177,6 @@ core_ll() {
 	for line in "${iall[@]}" ; do
 		if [ -f "$line" ] ; then
 			f1="$line"
-			ff1="$(realpath -q "$f1")"
 			_length="$_lengtho"
 			dur="$(getdur)"
 			getiparam
@@ -201,16 +197,16 @@ core_ll() {
 				fi
 				core --start="$_start" --length="$_length" "$@"
 			done
-			echo "$(scr1pt): Loop Pattern playlist: ${ff1},$(tr '[:blank:]' ',' <<< "${lpatpl[*]}")"
+			echo "${scp}: Clip Pattern playlist: ${lpatpl[*]}"
 			unset lpatpl
 			unset _start
 			unset iterin
 		else
 			if grep -q '[^[:space:]]' <<< "$line" ; then
 				if [ ${#line} -gt 90 ] ; then
-					echo >&2 "$(scr1pt): WARNING: Not a regular file - skipping: ${line:0:45}...${line: -45}"
+					echo >&2 "${scp}: WARNING: Not a regular file - skipping: ${line:0:45}...${line: -45}"
 				else
-					echo >&2 "$(scr1pt): WARNING: Not a regular file - skipping: $line"
+					echo >&2 "${scp}: WARNING: Not a regular file - skipping: $line"
 				fi
 			fi
 		fi
@@ -218,9 +214,9 @@ core_ll() {
 }
 
 if (("$#" == 0)) ; then
-	echo "$(scr1pt): Usage: $(scr1pt) {[<mpv profile,...>] <clip duration> <interval scale> [-l|-s|-t] [path/]filename | --help | --version}"
+	echo "${scp}: Usage: ${scp} {[<mpv profile,...>] <clip duration> <interval scale> [-l|-s|-t] [path/]filename | --help | --version}"
 elif [ '--version' = "$1" ] ; then
-	echo "mpvival 1.0"
+	echo "mpvival 1.1"
 elif [ '--help' = "$1" ] ; then
 	cat << '_EOF_'
 MPVIVAL - run MPV adjusted at intervals of the total duration of a file
@@ -358,18 +354,18 @@ elif [ '-l' = "$3" ] || [ '-ls' = "$3" ] || [ '-sl' = "$3" ] || [ '-tl' = "$3" ]
 					core_ll
 				fi
 			else
-				echo >&2 "$(scr1pt): WARNING: Empty file: $4"
-				echo "$(scr1pt): Help summary: $(scr1pt) --help"
+				echo >&2 "${scp}: WARNING: Empty file: $4"
+				echo "${scp}: Help summary: ${scp} --help"
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist: $4"
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist: $4"
+			echo "${scp}: Help summary: ${scp} --help"
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist."
+		echo "${scp}: Help summary: ${scp} --help"
 	fi
-	echo "$(scr1pt): ${iterout:-0} iterations completed - exiting..."
+	echo "${scp}: ${iterout:-0} iterations completed - exiting..."
 elif [ '-t' = "$3" ] || [ '-ts' = "$3" ] || [ '-st' = "$3" ] && grep -qE "^[1-5]$" <<< "$2" && grep -qE "^[0-9]+$" <<< "$1" && (("$1" > 0)) ; then
 	swreq
 	_lengtho="$1"
@@ -395,7 +391,7 @@ elif [ '-t' = "$3" ] || [ '-ts' = "$3" ] || [ '-st' = "$3" ] && grep -qE "^[1-5]
 			elif [ -f "$f2" ] ; then
 				iall2+=("$f2")
 			else
-				echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+				echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 			fi
 		done
 		if [ -v shuffle ] ; then
@@ -404,18 +400,17 @@ elif [ '-t' = "$3" ] || [ '-ts' = "$3" ] || [ '-st' = "$3" ] && grep -qE "^[1-5]
 			iall1+=("${iall2[@]}")
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	for (( ival=1 ; ival<=scal ; ival++ )) ; do
 		for f1 in "${iall1[@]}" ; do
-			ff1="$(realpath -q "$f1")"
 			_length="$_lengtho"
 			dur="$(getdur)"
 			if ((_length > dur)) ; then
 				_length="$dur"
-				echo "$(scr1pt): INFO: Clip duration reset: ${dur}s"
+				echo "${scp}: INFO: Clip duration reset: ${dur}s"
 			fi
 			idur="$dur"
 			ivals="$scal"
@@ -434,7 +429,7 @@ elif [ '-t' = "$3" ] || [ '-ts' = "$3" ] || [ '-st' = "$3" ] && grep -qE "^[1-5]
 			unset _start
 		done
 	done
-	echo "$(scr1pt): ${iterout:-0} iterations completed - exiting..."
+	echo "${scp}: ${iterout:-0} iterations completed - exiting..."
 elif [ '-l' = "$4" ] || [ '-ls' = "$4" ] || [ '-sl' = "$4" ] || [ '-tl' = "$4" ] || [ '-lt' = "$4" ] || [ '-lst' = "$4" ] || [ '-lts' = "$4" ] || [ '-tls' = "$4" ] || [ '-tsl' = "$4" ] || [ '-slt' = "$4" ] || [ '-stl' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 	swreq
 	if grep -qE "^[0-9]+$" <<< "$1" && (("$1" > 0)) ; then
@@ -446,8 +441,8 @@ elif [ '-l' = "$4" ] || [ '-ls' = "$4" ] || [ '-sl' = "$4" ] || [ '-tl' = "$4" ]
 		_lengtho="$2"
 		scal="$3"
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	if [ '-ls' = "$4" ] || [ '-sl' = "$4" ] || [ '-lst' = "$4" ] || [ '-lts' = "$4" ] || [ '-tls' = "$4" ] || [ '-tsl' = "$4" ] || [ '-slt' = "$4" ] || [ '-stl' = "$4" ] ; then
@@ -463,18 +458,18 @@ elif [ '-l' = "$4" ] || [ '-ls' = "$4" ] || [ '-sl' = "$4" ] || [ '-tl' = "$4" ]
 					core_ll --profile="$prf"
 				fi
 			else
-				echo >&2 "$(scr1pt): WARNING: Empty file: $5"
-				echo "$(scr1pt): Help summary: $(scr1pt) --help"
+				echo >&2 "${scp}: WARNING: Empty file: $5"
+				echo "${scp}: Help summary: ${scp} --help"
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist: $5"
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist: $5"
+			echo "${scp}: Help summary: ${scp} --help"
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist."
+		echo "${scp}: Help summary: ${scp} --help"
 	fi
-	echo "$(scr1pt): ${iterout:-0} iterations completed - exiting..."
+	echo "${scp}: ${iterout:-0} iterations completed - exiting..."
 elif [ '-t' = "$4" ] || [ '-ts' = "$4" ] || [ '-st' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 	swreq
 	if grep -qE "^[0-9]+$" <<< "$1" && (("$1" > 0)) ; then
@@ -486,8 +481,8 @@ elif [ '-t' = "$4" ] || [ '-ts' = "$4" ] || [ '-st' = "$4" ] && grep -qE "^[1-5]
 		_lengtho="$2"
 		scal="$3"
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	iterin=1
@@ -511,7 +506,7 @@ elif [ '-t' = "$4" ] || [ '-ts' = "$4" ] || [ '-st' = "$4" ] && grep -qE "^[1-5]
 			elif [ -f "$f2" ] ; then
 				iall2+=("$f2")
 			else
-				echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+				echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 			fi
 		done
 		if [ -v shuffle ] ; then
@@ -520,18 +515,17 @@ elif [ '-t' = "$4" ] || [ '-ts' = "$4" ] || [ '-st' = "$4" ] && grep -qE "^[1-5]
 			iall1+=("${iall2[@]}")
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	for (( ival=1 ; ival<=scal ; ival++ )) ; do
 		for f1 in "${iall1[@]}" ; do
-			ff1="$(realpath -q "$f1")"
 			_length="$_lengtho"
 			dur="$(getdur)"
 			if ((_length > dur)) ; then
 				_length="$dur"
-				echo "$(scr1pt): INFO: Clip duration reset: ${dur}s"
+				echo "${scp}: INFO: Clip duration reset: ${dur}s"
 			fi
 			idur="$dur"
 			ivals="$scal"
@@ -550,7 +544,7 @@ elif [ '-t' = "$4" ] || [ '-ts' = "$4" ] || [ '-st' = "$4" ] && grep -qE "^[1-5]
 			unset _start
 		done
 	done
-	echo "$(scr1pt): ${iterout:-0} iterations completed - exiting..."
+	echo "${scp}: ${iterout:-0} iterations completed - exiting..."
 elif [ -e "$3" ] || [ '-s' = "$3" ] && grep -qE "^[1-5]$" <<< "$2" && grep -qE "^[0-9]+$" <<< "$1" && (("$1" > 0)) ; then
 	swreq
 	_lengtho="$1"
@@ -577,7 +571,7 @@ elif [ -e "$3" ] || [ '-s' = "$3" ] && grep -qE "^[1-5]$" <<< "$2" && grep -qE "
 			elif [ -f "$f2" ] ; then
 				iall2+=("$f2")
 			else
-				echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+				echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 			fi
 		done
 		if [ -v shuffle ] ; then
@@ -586,12 +580,11 @@ elif [ -e "$3" ] || [ '-s' = "$3" ] && grep -qE "^[1-5]$" <<< "$2" && grep -qE "
 			iall1+=("${iall2[@]}")
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	for f1 in "${iall1[@]}" ; do
-		ff1="$(realpath -q "$f1")"
 		_length="$_lengtho"
 		dur="$(getdur)"
 		getiparam
@@ -612,12 +605,12 @@ elif [ -e "$3" ] || [ '-s' = "$3" ] && grep -qE "^[1-5]$" <<< "$2" && grep -qE "
 			fi
 			core --start="$_start" --length="$_length"
 		done
-		echo "$(scr1pt): Loop Pattern playlist: ${ff1},$(tr '[:blank:]' ',' <<< "${lpatpl[*]}")"
+		echo "${scp}: Clip Pattern playlist: ${lpatpl[*]}"
 		unset lpatpl
 		unset _start
 		unset iterin
 	done
-	echo "$(scr1pt): ${iterout:-0} iterations completed - exiting..."
+	echo "${scp}: ${iterout:-0} iterations completed - exiting..."
 elif [ -e "$4" ] || [ '-s' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 	swreq
 	if grep -qE "^[0-9]+$" <<< "$1" && (("$1" > 0)) ; then
@@ -629,8 +622,8 @@ elif [ -e "$4" ] || [ '-s' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 		_lengtho="$2"
 		scal="$3"
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	if [ '-s' = "$4" ] ; then
@@ -655,7 +648,7 @@ elif [ -e "$4" ] || [ '-s' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 			elif [ -f "$f2" ] ; then
 				iall2+=("$f2")
 			else
-				echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+				echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 			fi
 		done
 		if [ -v shuffle ] ; then
@@ -664,12 +657,11 @@ elif [ -e "$4" ] || [ '-s' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 			iall1+=("${iall2[@]}")
 		fi
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 		exit 1
 	fi
 	for f1 in "${iall1[@]}" ; do
-		ff1="$(realpath -q "$f1")"
 		_length="$_lengtho"
 		dur="$(getdur)"
 		getiparam
@@ -690,13 +682,13 @@ elif [ -e "$4" ] || [ '-s' = "$4" ] && grep -qE "^[1-5]$" <<< "$3" ; then
 			fi
 			core --start="$_start" --length="$_length" --profile="$prf"
 		done
-		echo "$(scr1pt): Loop Pattern playlist: ${ff1},$(tr '[:blank:]' ',' <<< "${lpatpl[*]}")"
+		echo "${scp}: Clip Pattern playlist: ${lpatpl[*]}"
 		unset lpatpl
 		unset _start
 		unset iterin
 	done
-	echo "$(scr1pt): ${iterout:-0} iterations completed - exiting..."
+	echo "${scp}: ${iterout:-0} iterations completed - exiting..."
 else
-	echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-	echo "$(scr1pt): Help summary: $(scr1pt) --help"
+	echo >&2 "${scp}: WARNING: Invalid options - aborting."
+	echo "${scp}: Help summary: ${scp} --help"
 fi
diff --git a/mpvloop b/mpvloop
--- a/mpvloop
+++ b/mpvloop
@@ -24,15 +24,13 @@ q=1
 # Field delimiter in a playlist
 d=,
 
-scr1pt() {
-	basename "$0"
-}
+scp="$(basename "$0")"
 
 swreq() {
-	type awk >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: AWK not found - aborting."; exit 1; }
-	type file >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: FILE (command) not found - aborting."; exit 1; }
-	type grep >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: GREP not found - aborting."; exit 1; }
-	type mpv >/dev/null 2>&1 || { echo >&2 "$(scr1pt): WARNING: MPV not found - aborting."; exit 1; }
+	type awk >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: AWK not found - aborting."; exit 1; }
+	type file >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: FILE (command) not found - aborting."; exit 1; }
+	type grep >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: GREP not found - aborting."; exit 1; }
+	type mpv >/dev/null 2>&1 || { echo >&2 "${scp}: WARNING: MPV not found - aborting."; exit 1; }
 }
 
 lpat_tt() {
@@ -59,14 +57,14 @@ lpat_b() {
 }
 
 uquit() {
-	echo "$(scr1pt): INFO: Press any key to exit the script or skip the file."
+	echo "${scp}: INFO: Press any key to exit the script or skip the file."
 	if read -rst "$q" -N 1 ; then
-		echo "$(scr1pt): File: $f1"
-		echo "$(scr1pt): Please confirm:"
+		echo "${scp}: File: $f1"
+		echo "${scp}: Please confirm:"
 		select ans in "EXIT the script" "SKIP file" "Cancel" ; do
 			case "$ans" in
 				'EXIT the script' )
-					echo "$(scr1pt): $((iter - 1)) iterations completed - exiting..."
+					echo "${scp}: $((iter - 1)) iterations completed - exiting..."
 					exit;;
 				'SKIP file' )
 					return 1;;
@@ -80,31 +78,31 @@ uquit() {
 
 core() {
 	if [ "$aa" -eq 0 ] && [ "$bb" -eq 0 ] ; then
-		echo "$(scr1pt): Loop pattern: $(grep -oE "$lpat" <<< "$ab") (file)"
-		echo "$(scr1pt): Options: --loop-file=inf" "$@"
-		echo "$(scr1pt): Starting mpv..."
+		echo "${scp}: Loop pattern: $(grep -oE "$lpat" <<< "$ab") (file)"
+		echo "${scp}: Options: --loop-file=inf" "$@"
+		echo "${scp}: Starting mpv..."
 		mpv --loop-file=inf "$@" "$f1"
 		return
 	elif [ "$aa" -eq 0 ] ; then
 		b=$(lpat_b)
-		echo "$(scr1pt): Loop pattern and duration: $(grep -oE "$lpat" <<< "$ab") (${b}s)"
-		echo "$(scr1pt): Options: --ab-loop-a=no --ab-loop-b=$b" "$@"
-		echo "$(scr1pt): Starting mpv..."
+		echo "${scp}: Loop pattern and duration: $(grep -oE "$lpat" <<< "$ab") (${b}s)"
+		echo "${scp}: Options: --ab-loop-a=no --ab-loop-b=$b" "$@"
+		echo "${scp}: Starting mpv..."
 		mpv --ab-loop-a=no --ab-loop-b="$b" "$@" "$f1"
 		return
 	elif [ "$bb" -eq 0 ] ; then
 		a=$(lpat_a)
-		echo "$(scr1pt): Loop pattern: $(grep -oE "$lpat" <<< "$ab")"
-		echo "$(scr1pt): Options: --start=$a --ab-loop-a=$a --ab-loop-b=no" "$@"
-		echo "$(scr1pt): Starting mpv..."
+		echo "${scp}: Loop pattern: $(grep -oE "$lpat" <<< "$ab")"
+		echo "${scp}: Options: --start=$a --ab-loop-a=$a --ab-loop-b=no" "$@"
+		echo "${scp}: Starting mpv..."
 		mpv --start="$a" --ab-loop-a="$a" --ab-loop-b=no "$@" "$f1"
 		return
 	fi
 	a=$(lpat_a)
 	b=$(lpat_b)
-	echo "$(scr1pt): Loop pattern and duration: $(grep -oE "$lpat" <<< "$ab") ($(awk "BEGIN { print ( $bb * $sc ) - ( $aa * $sc ) }")s)"
-	echo "$(scr1pt): Options: --start=$a --ab-loop-a=$a --ab-loop-b=$b" "$@"
-	echo "$(scr1pt): Starting mpv..."
+	echo "${scp}: Loop pattern and duration: $(grep -oE "$lpat" <<< "$ab") ($(awk "BEGIN { print ( $bb * $sc ) - ( $aa * $sc ) }")s)"
+	echo "${scp}: Options: --start=$a --ab-loop-a=$a --ab-loop-b=$b" "$@"
+	echo "${scp}: Starting mpv..."
 	mpv --start="$a" --ab-loop-a="$a" --ab-loop-b="$b" "$@" "$f1"
 }
 
@@ -118,10 +116,10 @@ core_ll() {
 		f1="$(cut -d "$d" -f 1 <<< "$line")"
 		if [ ! -f "$f1" ] || grep -qv "$d" <<< "$line" ; then
 			if [ ${#line} -gt 90 ] ; then
-				echo >&2 "$(scr1pt): WARNING: No field separator or file - skipping: ${line:0:45}...${line: -45}"
+				echo >&2 "${scp}: WARNING: No field separator or file - skipping: ${line:0:45}...${line: -45}"
 				continue
 			else
-				echo >&2 "$(scr1pt): WARNING: No field separator or file - skipping: $line"
+				echo >&2 "${scp}: WARNING: No field separator or file - skipping: $line"
 				continue
 			fi
 		fi
@@ -139,7 +137,7 @@ core_ll() {
 				fi
 				core "$@"
 			else
-				echo >&2 "$(scr1pt): WARNING: Invalid loop pattern - skipping: $ab"
+				echo >&2 "${scp}: WARNING: Invalid loop pattern - skipping: $ab"
 				continue
 			fi
 		done
@@ -162,7 +160,7 @@ if [ -e "$1" ] ; then
 		elif [ -f "$f2" ] ; then
 			iall1+=("$f2")
 		else
-			echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+			echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 		fi
 	done
 	for f1 in "${iall1[@]}" ; do
@@ -181,10 +179,10 @@ if [ -e "$1" ] ; then
 				core
 			done
 		else
-			echo >&2 "$(scr1pt): WARNING: No loop pattern - skipping: $(basename "$f1")"
+			echo >&2 "${scp}: WARNING: No loop pattern - skipping: $(basename "$f1")"
 		fi
 	done
-	echo "$(scr1pt): ${iter:-0} iterations completed - exiting..."
+	echo "${scp}: ${iter:-0} iterations completed - exiting..."
 elif [ '--help' = "$1" ] ; then
 	cat << '_EOF_'
 MPVLOOP - run MPV with loop options set according to a pattern.
@@ -314,7 +312,7 @@ instead of seconds.
 l ab-loop ; print-text "ab-loop=${=time-pos}"
 _EOF_
 elif [ '--version' = "$1" ] ; then
-	echo "mpvloop 1.0"
+	echo "mpvloop 1.1"
 elif [ '--lpat' = "$1" ] ; then
 	swreq
 	if [ -n "$2" ] ; then
@@ -346,12 +344,12 @@ elif [ '--lpat' = "$1" ] ; then
 					printf "%s\\t%s\\n" "$lpat_ab" "(${tt})"
 				fi
 			else
-				echo >&2 "$(scr1pt): WARNING: Invalid timestamp format - skipping: $tt"
+				echo >&2 "${scp}: WARNING: Invalid timestamp format - skipping: $tt"
 			fi
 		done
 	else
-		echo "$(scr1pt): Usage: $(scr1pt) --lpat <HH:MM:SS[.n]-HH:MM:SS[.n] | HH:MM:SS[.n]- | -HH:MM:SS[.n]>..."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo "${scp}: Usage: ${scp} --lpat <HH:MM:SS[.n]-HH:MM:SS[.n] | HH:MM:SS[.n]- | -HH:MM:SS[.n]>..."
+		echo "${scp}: Help summary: ${scp} --help"
 
 	fi
 elif [ '-l' = "$1" ] || [ '-ls' = "$1" ] || [ '-sl' = "$1" ] ; then
@@ -365,19 +363,19 @@ elif [ '-l' = "$1" ] || [ '-ls' = "$1" ] || [ '-sl' = "$1" ] ; then
 				loopfile="$2"
 				core_ll
 			else
-				echo >&2 "$(scr1pt): WARNING: Empty file: $2"
-				echo "$(scr1pt): Help summary: $(scr1pt) --help"
+				echo >&2 "${scp}: WARNING: Empty file: $2"
+				echo "${scp}: Help summary: ${scp} --help"
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist: $2"
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist: $2"
+			echo "${scp}: Help summary: ${scp} --help"
 		fi
 	else
 		shift
-		echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist:" "$@"
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist:" "$@"
+		echo "${scp}: Help summary: ${scp} --help"
 	fi
-	echo "$(scr1pt): ${iter:-0} iterations completed - exiting..."
+	echo "${scp}: ${iter:-0} iterations completed - exiting..."
 elif [ '-l' = "$2" ] || [ '-ls' = "$2" ] || [ '-sl' = "$2" ] ; then
 	swreq
 	if [ "$#" -eq 3 ] && [ -r "$3" ] ; then
@@ -389,20 +387,22 @@ elif [ '-l' = "$2" ] || [ '-ls' = "$2" ] || [ '-sl' = "$2" ] ; then
 				loopfile="$3"
 				core_ll --profile="$1"
 			else
-				echo >&2 "$(scr1pt): WARNING: Empty file: $3"
-				echo "$(scr1pt): Help summary: $(scr1pt) --help"
+				echo >&2 "${scp}: WARNING: Empty file: $3"
+				echo "${scp}: Help summary: ${scp} --help"
 			fi
 		else
-			echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist: $3"
-			echo "$(scr1pt): Help summary: $(scr1pt) --help"
+			echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist: $3"
+			echo "${scp}: Help summary: ${scp} --help"
 		fi
 	else
 		shift 2
-		echo >&2 "$(scr1pt): WARNING: A single plaintext file is expected for playlist:" "$@"
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: A single plaintext file is expected for playlist:" "$@"
+		echo "${scp}: Help summary: ${scp} --help"
 	fi
-	echo "$(scr1pt): ${iter:-0} iterations completed - exiting..."
-elif grep -oqE ^"${lpat}"\$ <<< "$2" || grep -oqE ^"${lpat}"\$ <<< "$1" || [ -e "$2" ] ; then
+	echo "${scp}: ${iter:-0} iterations completed - exiting..."
+elif [ "$#" -eq 0 ] ; then
+	echo "${scp}: Usage: ${scp} {[<mpv profile,...>] [<loop pattern>... | -l] [-s] [path/]filename | --lpat <timestamp range>... | --help | --version}"
+else
 	swreq
 	for arg in "$@" ; do
 		iterin=$((iterin + 1))
@@ -418,7 +418,7 @@ elif grep -oqE ^"${lpat}"\$ <<< "$2" || grep -oqE ^"${lpat}"\$ <<< "$1" || [ -e 
 			if [ ! -v prf ] ; then
 				prf="$arg"
 			else
-				echo >&2 "$(scr1pt): WARNING: MPV profile already set to ${prf@Q} - skipping: $arg"
+				echo >&2 "${scp}: WARNING: MPV profile already set to ${prf@Q} - skipping: $arg"
 			fi
 		fi
 	done
@@ -438,7 +438,7 @@ elif grep -oqE ^"${lpat}"\$ <<< "$2" || grep -oqE ^"${lpat}"\$ <<< "$1" || [ -e 
 			elif [ -f "$f2" ] ; then
 				iall2+=("$f2")
 			else
-				echo >&2 "$(scr1pt): WARNING: No such file or directory - skipping: $f2"
+				echo >&2 "${scp}: WARNING: No such file or directory - skipping: $f2"
 			fi
 		done
 		if [ -v shuffle ] ; then
@@ -485,18 +485,13 @@ elif grep -oqE ^"${lpat}"\$ <<< "$2" || grep -oqE ^"${lpat}"\$ <<< "$1" || [ -e 
 						fi
 					done
 				else
-					echo >&2 "$(scr1pt): WARNING: No loop pattern - skipping: $(basename "$f1")"
+					echo >&2 "${scp}: WARNING: No loop pattern - skipping: $(basename "$f1")"
 				fi
 			fi
 		done
 	else
-		echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-		echo "$(scr1pt): Help summary: $(scr1pt) --help"
+		echo >&2 "${scp}: WARNING: Invalid options - aborting."
+		echo "${scp}: Help summary: ${scp} --help"
 	fi
-	echo "$(scr1pt): ${iter:-0} iterations completed - exiting..."
-elif [ "$#" -eq 0 ] ; then
-	echo "$(scr1pt): Usage: $(scr1pt) {[<mpv profile,...>] [<loop pattern>... | -l] [-s] [path/]filename | --lpat <timestamp range>... | --help | --version}"
-else
-	echo >&2 "$(scr1pt): WARNING: Invalid options - aborting."
-	echo "$(scr1pt): Help summary: $(scr1pt) --help"
+	echo "${scp}: ${iter:-0} iterations completed - exiting..."
 fi
